version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: drs__php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #Redis Service
  redis:
    container_name: drs__redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
